parameters:
  jobName: release
  imageName: windows-latest
  displayName: 'Release Microsoft.PowerShell.SecretManagement to NuGet'

jobs:
- job: ${{ parameters.jobName }}
  pool:
    vmImage: ${{ parameters.imageName }}
  displayName: ${{ parameters.displayName }}

  steps:
  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet 5.6.0'
    inputs:
      checkLatest: false
      version: 5.6.0

  - task: DownloadBuildArtifacts@0
    displayName: 'Download SecretManagement module artifacts'
    inputs:
      buildType: current
      downloadType: specific
      artifactName: '**/*.nupkg'
      downloadPath: '$(System.ArtifactsDirectory)'

  - powershell: |
      Get-ChildItem '$(System.ArtifactsDirectory)/nupkg/Microsoft.PowerShell.SecretManagement.*.nupkg' -ErrorAction SilentlyContinue
      Get-ChildItem '$(System.ArtifactsDirectory)/RefAssemblyNuGet/Microsoft.PowerShell.SecretManagement.Library*.nupkg' -ErrorAction SilentlyContinue
      # Get-ChildItem '$(System.ArtifactsDirectory)' -Recurse
    displayName: 'Capture SecretManagement NuGet packages'

  #- task: NuGetCommand@2
  #  displayName: 'Push Microsoft.PowerShell.SecretManagement.Library reference assembly nuget package to NuGet'
  #  inputs:
  #    command: push
  #    packagesToPush: '$(System.ArtifactsDirectory)/RefAssemblyNuGet/Microsoft.PowerShell.SecretManagement.Library*.nupkg'
  #    nuGetFeedType: external
  #    publishFeedCredentials: PowerShellNuGetOrgPush

  #- task: NuGetCommand@2
  #  displayName: 'Push Microsoft.PowerShell.SecretManagement module artifacts to PSGallery feed'
  #  inputs:
  #    command: push
  #    packagesToPush: '$(System.ArtifactsDirectory)/nupkg/Microsoft.PowerShell.SecretManagement.*.nupkg'
  #    nuGetFeedType: external
  #    publishFeedCredentials: PHPowerShellGalleryFeed
