parameters:
  jobName: release
  displayName: 'Release Microsoft.PowerShell.SecretManagement to PSGallery'

jobs:
- job: ${{ parameters.jobName }}
  pool:
    name: 1ES
    demands:
    - ImageOverride -equals MMS2019
  displayName: ${{ parameters.displayName }}

  steps:

  - task: DownloadPipelineArtifact@2
    displayName: 'Download SecretManagement module artifacts'
    inputs:
      artifact: nupkg
      patterns: '**/*.nupkg'
      downloadPath: '$(Pipeline.Workspace)/nuget'

  - powershell: |
      $package = (Get-ChildItem '$(Pipeline.Workspace)/nuget/Microsoft.PowerShell.SecretManagement.*.nupkg').FullName
      $package
      $vstsCommandString = "vso[task.setvariable variable=NugetPkgPath]${package}"
      Write-Host "sending " + $vstsCommandString
      Write-Host "##$vstsCommandString"
    displayName: 'Capture SecretManagement NuGet package path and set environment variable'

  - task: NuGetCommand@2
    displayName: 'Push Microsoft.PowerShell.SecretManagement module artifacts to PSGallery feed'
    inputs:
      command: push
      packagesToPush: '$(NugetPkgPath)'
      nuGetFeedType: external
      publishFeedCredentials: PSGalleryPush

  #- task: NuGetCommand@2
  #  displayName: 'Push Microsoft.PowerShell.SecretManagement.Library reference assembly nuget package to NuGet'
  #  inputs:
  #    command: push
  #    packagesToPush: '$(System.ArtifactsDirectory)/RefAssemblyNuGet/Microsoft.PowerShell.SecretManagement.Library*.nupkg'
  #    nuGetFeedType: external
  #    publishFeedCredentials: PowerShellNuGetOrgPush
