name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  merge_group:
    types: [ checks_requested ]

jobs:
  ci:
    name: pester
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - run: ./tools/installPSResources.ps1
        shell: pwsh
      - run: ./build.ps1 -Build && Invoke-ModuleTests -Type Functional
        shell: pwsh
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: SecretManagement-package-${{ matrix.os }}
          path: out/**/*.nupkg
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: SecretManagement-tests-${{ matrix.os }}
          path:  test/result.pester.xml
