name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    types: [ checks_requested ]

jobs:
  ci:
    name: pester
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          cache: true
          cache-dependency-path: '**/*.csproj'
          dotnet-version: 8.x
      - run: ./tools/installPSResources.ps1
        shell: pwsh
      - run: Invoke-Build -Configuration Release -Task Build, Package, Test
        shell: pwsh
      - run: |
           Install-Module Pester -Scope CurrentUser -Force -SkipPublisherCheck
           Invoke-Pester Test
        if: matrix.os == 'windows-latest'
        shell: powershell
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: SecretManagement-package-${{ matrix.os }}
          path: out/**/*.nupkg
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: SecretManagement-tests-${{ matrix.os }}
          path: testResults.xml
